### ISSUE TITLE
Integrate Dionaea with MHN or similar project

### ISSUE THREAD

**Issue by ghost** [DinoTools/dionaea#117]
Is any way to integrate this version Dionaea with MHN project or similar project to collecting statistic about numbers of attacks and captured malware into one GUI console from all Dionaeas honeypot's machines?

**Comment by phibos** [comment]
The patches to the hpfeed code from the mhn project have been merged into the master branch a long time ago and haven't changed since then. So this should still work. I would recommend to create a new issue on the mhn project so they can update their deployment scripts to use the latest version.

If you are looking for a similar project you might want to have a look at http://dtag-dev-sec.github.io/

You can also use the [log_json incident handler](https://dionaea.readthedocs.io/en/latest/ihandler/log_json.html) in combination with an [ELK stack](https://www.elastic.co/)

**Comment by Svenito** [comment]
I am using this version of dionaea with the current mhn without any issues. So hpfeeds seems to be working

**Comment by br1877** [comment]
@Svenito Greate to know, but how to make it to works together?

**Comment by Svenito** [comment]
I followed these instructions

http://www.adlice.com/catch-malware-with-your-own-honeypot-v2/

**Comment by br1877** [comment]
Thanks a lot. That clears up many things, but still I do not understand this instruction:

`IDENT=myuuid
SECRET=mysecret
PUBLISH_CHANNELS="dionaea.capture,dionaea.connections"
SUBSCRIBE_CHANNELS=""

cd /opt/hpfeeds/broker
python add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHANNELS" "$SUBSCRIBE_CHANNELS"`

Is this a script or what? And what is it the "Secret"?

I followed:

```
cd /opt/hpfeeds/broker
python add_user.py "$dc306aea-57e9-11e7-........" "$SECRET_is_this_pass_to_MHN?" "$dionaea.capture,dionaea.connections" "$SUBSCRIBE_CHANNELS" 
```
But of course with errors.

**Comment by br1877** [comment]
My problem was solved. Required root privileges. Thanks :+1:

**Comment by br1877** [comment]
@Svenito If I create a new sensor (using this command: python add_user.py "$IDENT" "$SECRET" "$PUBLISH_CHANNELS" "$SUBSCRIBE_CHANNELS"), why is adding my home address IP into MHN console instead IP VPS machine where dionaea is works?

**Comment by phibos** [comment]
Closing the issue because it has been superseded by #132.
