### ISSUE TITLE
Kibana, ELK or another Dashboard

### ISSUE THREAD

**Issue by ghost** [DinoTools/dionaea#134]
Is any way to integrate Dionaea honetypots with Kibana, ELK or another Dashboard instead MHN project?

**Comment by ixiss78** [comment]
Hi,

It's been a while since you asked this question, but you can use the log_json ihandler to upload logs directly to elastic search. The logs are not fully complete (missing the executed command in ftp mode, or missing the wanted folder in SMB) but if you couple that with customized log parsing then you can get full logs on Kibana !

**Comment by t3chn0m4g3** [comment]
If Kibana is of interest you might want to have a look at [T-Pot](https://github.com/dtag-dev-sec/tpotce).
